version: '3'

services:
  ctrlinvest-api:
    image: ctrlinvest:latest
    build:
      context: .
      dockerfile: Dockerfile      
    ports:
      - "8000:8000"
    environment:
       - ASPNETCORE_ENVIRONMENT=Production
       - PORT=8000
    #    - USER_SECRETS_ID="d221a86e-bf92-4016-9b26-86e057ce4de7"
    # volumes:
    #   - /mnt/c/Users/julia/AppData/Roaming/Microsoft/UserSecrets/d221a86e-bf92-4016-9b26-86e057ce4de7:/root/.microsoft/usersecrets/d221a86e-bf92-4016-9b26-86e057ce4de7