version: '3'

services:
  ctrlinvest-postgres:
    image: postgres
    container_name: "ctrlinvest-postgres"
    environment:
      POSTGRES_DB: "ctrlinvestDB"
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "15433:5432"
    networks:
      - ctrlinvest-postgres-network
      
  ctrlinvest-pgadmin:
    image: dpage/pgadmin4
    container_name: "ctrlinvest-pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: "juliano.pestili@outlook.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "16544:80"
    depends_on:
      - ctrlinvest-postgres
    networks:
      - ctrlinvest-postgres-network

networks: 
  ctrlinvest-postgres-network:
    driver: bridge