version: '3'

services:
  ctrl-invest-api:
    image: ctrl-invest:latest
    container_name: "ctrl-invest-app-${ENVIRONMENT}"    
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8002:80"
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - PORT=8002
       - ElasticConfiguration__Uri=http://172.17.0.1:9200
       - HealthChecksUI__HealthChecks__0__Uri=http://172.17.0.1:8002/health
       - ConnectionStrings__DefaultConnection=User ID =postgres;Password=${DATABASE_DEFAULT_PASSWORD};Server=ctrl-invest-db;Port=5432;Database=ctrl-invest-db-${ENVIRONMENT};Integrated Security=true;Pooling=true;
    networks:
      - ctrl-invest-network
    links:
      - ctrl-invest-db
    depends_on:
      ctrl-invest-db:
        condition: service_healthy
  ctrl-invest-db:
    image: postgres:latest
    container_name: "ctrl-invest-db-${ENVIRONMENT}"
    restart: always
    ports:
      - "15432:5432"
    volumes: 
      - /home/juliano/volume-db-data/ctrlinvest:/var/lib/postgresql/data      
    environment:
      POSTGRES_DB: "ctrl-invest-db-${ENVIRONMENT}"
      POSTGRES_PASSWORD: "${DATABASE_DEFAULT_PASSWORD}"
    networks:
      - ctrl-invest-network      
    healthcheck:
      test: "pg_isready -q -U postgres"
networks:
  ctrl-invest-network:
    name: ctrl-invest-network