version: '3'

services:
  ctrlinvest-receive-data:
    image: receive-data:latest
    build:
      context: ../
      dockerfile: Dockerfile-Receive-Data
    environment:
       - DOTNET_ENVIRONMENT=Development
       - 'RabbitConfig:HostName=172.17.0.1'
    networks:
      - ctrl-invest-dev-net
networks:
  ctrl-invest-dev-net:
    external: true