version: '3'

services:
  ctrlinvest-import-earnings:
    image: import-earning:latest
    build:
      context: ../
      dockerfile: Dockerfile-Import-Dividends
    environment:
       - DOTNET_ENVIRONMENT=Development
  ctrlinvest-import-historical:
    image: import-historical:latest
    build:
      context: ../
      dockerfile: Dockerfile-Import-Historical
    environment:
       - DOTNET_ENVIRONMENT=Development
  ctrlinvest-receive-data:
    image: receive-data:latest
    build:
      context: ../
      dockerfile: Dockerfile-Receive-Data
    environment:
       - DOTNET_ENVIRONMENT=Development              
